#!/bin/sh
# COLOR_STARTS
# Shell variables
# Generated by 'wal'
wallpaper='/home/nikola/Pictures/wallpapers/Jagged.png'

# Special
background='#120619'
foreground='#92c7d7'
cursor='#92c7d7'

# Colors
color0='#120619'
color1='#A90654'
color2='#EF9E05'
color3='#F5CB03'
color4='#293E87'
color5='#1C6093'
color6='#E6319D'
color7='#92c7d7'
color8='#668b96'
color9='#A90654'
color10='#EF9E05'
color11='#F5CB03'
color12='#293E87'
color13='#1C6093'
color14='#E6319D'
color15='#92c7d7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
# COLOR_ENDS
chosen=$(ls /home/nikola/.screenlayout | dmenu  -i -p 'Change screen layout?' -nb $color0 -sf $color0  -sb $color2  -nf $color2 )
sh "/home/nikola/.screenlayout/$chosen"


