icons = "awesome5"

[theme]
file = "/home/nikola/.config/i3status-rs/themes/customtheme.tomi"
[theme.overrides]

#separator = "\ue0b2"

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "temperature" 
collapsed = true
interval = 10
format = "{max}° max, {average}° avg"  
chip = "*-isa-*"

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{MUg}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "nvidia_gpu"
label = "GTX1060"
show_memory = true
show_clocks = true
interval = 1

[[block]]
block = "keyboard_layout"
driver = "localebus"

[[block]]
block = "sound"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} updates"
format_singular = "{pacman} update"
format_up_to_date = "U2D"
critical_updates_regex = "(linux |linux-lts|linux-zen)"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
